// Each expedition has its own route, machinery, story and visible outcome.
const mission = (
  id,
  title,
  location,
  x,
  z,
  resource,
  gather,
  action,
  success,
  effect,
  plus,
  minus,
  labels,
  model,
) => ({
  id,
  title,
  location,
  x,
  z,
  resource,
  gather,
  action,
  success,
  effect,
  goal: `${effect} Head to the ${location.toLowerCase()}.`,
  icon: ["fossil", "rescue", "launch"].includes(model) ? "spark" : "cube",
  plus,
  minus,
  labels,
  model,
});
export const ADVENTURES = {
  cavern: [
    mission(
      "ice",
      "Open the frozen mine",
      "Ice tunnel",
      4,
      11,
      "ice blocks",
      "Survey the frozen entrance",
      "Clear the tunnel",
      "The frozen passage is open!",
      "The ice breaks apart to reveal a glittering mine entrance.",
      "The left wall has {a} ice blocks and the right wall has {b}. How many blocks must the heater melt?",
      "There were {a} ice blocks sealing the mine. The sun melted {b}. How many blocks must the heater melt now?",
      [
        ["Left wall", "Right wall"],
        ["Sealing the mine", "Already melted"],
      ],
      "ice",
    ),
    mission(
      "rail",
      "Send the crystal express",
      "Mine railway",
      11,
      5,
      "crystals",
      "Check the mining crates",
      "Load the minecart",
      "All aboard the crystal express!",
      "A loaded minecart rolls along its mountain railway.",
      "Load {a} violet crystals and {b} blue crystals. How many crystals will the minecart carry?",
      "The cart has {a} crystals. Leave {b} at the mine. How many crystals will travel to the station?",
      [
        ["Violet crystals", "Blue crystals"],
        ["In the cart", "Leave behind"],
      ],
      "rail",
    ),
    mission(
      "lift",
      "Raise the mountain lift",
      "Summit lift",
      6,
      -2,
      "energy cells",
      "Inspect the lift battery",
      "Raise the lift",
      "Next stop: the summit!",
      "The cargo lift rises up its tall tower to the snowy lookout.",
      "The lift has {a} energy cells. Connect {b} more. How many cells will power the climb?",
      "There are {a} energy cells. {b} are empty. How many charged cells can power the lift?",
      [
        ["Connected", "Spare cells"],
        ["All cells", "Empty cells"],
      ],
      "lift",
    ),
    mission(
      "prism",
      "Catch a beam of starlight",
      "Prism laboratory",
      -5,
      -7,
      "light sparks",
      "Read the prism meters",
      "Turn on the prisms",
      "A ribbon of light crosses the peaks!",
      "Giant crystal prisms turn and send a beam of light through the snow.",
      "One prism catches {a} light sparks. Another catches {b}. How many sparks can light the mountain?",
      "A prism catches {a} light sparks. {b} escape into the sky. How many sparks are left in the beam?",
      [
        ["First prism", "Second prism"],
        ["Caught sparks", "Escaped sparks"],
      ],
      "prism",
    ),
    mission(
      "beacon",
      "Guide the climbers home",
      "Rescue beacons",
      4,
      -11,
      "signal flashes",
      "Read the rescue message",
      "Light the beacons",
      "The climbers can find their way home!",
      "Three glowing rescue towers send their signals across the mountains.",
      "The first rescue message has {a} flashes. Add {b} more. How many flashes are in the whole signal?",
      "The rescue signal needs {a} flashes. It has sent {b}. How many flashes are still needed?",
      [
        ["First message", "Extra flashes"],
        ["Whole signal", "Already sent"],
      ],
      "beacon",
    ),
  ],
  sunset: [
    mission(
      "dig",
      "Uncover a buried giant",
      "Fossil dig",
      6,
      12,
      "sand scoops",
      "Measure the sandy mound",
      "Excavate the fossil",
      "A dinosaur beneath the dunes!",
      "The sand falls away to reveal the ribs and skull of an ancient creature.",
      "The head is under {a} scoops of sand. The ribs are under {b}. How many scoops will uncover the fossil?",
      "There were {a} scoops of sand covering the fossil. You brushed away {b}. How many scoops are left?",
      [
        ["Over the head", "Over the ribs"],
        ["Covering the fossil", "Brushed away"],
      ],
      "fossil",
    ),
    mission(
      "water",
      "Fill the desert reservoir",
      "Oasis pump",
      11,
      3,
      "water buckets",
      "Read the water gauges",
      "Start the pump",
      "Water is flowing through the desert!",
      "A spinning pump fills the blue reservoir between the dunes.",
      "The first tank holds {a} buckets of water and the second holds {b}. How many buckets can fill the reservoir?",
      "The tank holds {a} buckets of water. Keep {b} for the travellers. How many buckets can fill the reservoir?",
      [
        ["First tank", "Second tank"],
        ["In the tank", "For travellers"],
      ],
      "pump",
    ),
    mission(
      "mosaic",
      "Rebuild the sun mosaic",
      "Mosaic courtyard",
      7,
      -6,
      "gold tiles",
      "Sort the ancient tiles",
      "Restore the mosaic",
      "The ancient sun shines again!",
      "Golden tiles rise into a giant sun pattern on the temple wall.",
      "You found {a} gold tiles in one chest and {b} in another. How many tiles can restore the sun?",
      "You found {a} gold tiles. {b} are broken. How many whole tiles can restore the sun?",
      [
        ["First chest", "Second chest"],
        ["Found tiles", "Broken tiles"],
      ],
      "mosaic",
    ),
    mission(
      "scale",
      "Lift the treasure door",
      "Balance chamber",
      -5,
      -9,
      "counterweights",
      "Inspect the stone balance",
      "Balance the hoist",
      "The treasure door is rising!",
      "The counterweight drops and lifts a huge stone door above the treasure.",
      "The hoist has {a} counterweights. Add {b} more. How many counterweights will lift the door?",
      "You have {a} counterweights. Remove {b} cracked ones. How many good counterweights can lift the door?",
      [
        ["On the hoist", "Ready to add"],
        ["All weights", "Cracked weights"],
      ],
      "scale",
    ),
    mission(
      "caravan",
      "Launch the sand sailor",
      "Desert dock",
      0,
      2,
      "supply crates",
      "Check the expedition cargo",
      "Send the sand sailor",
      "The expedition sails over the dunes!",
      "A bright sail opens and the sand ship sets out on its next expedition.",
      "Load {a} food crates and {b} tool crates. How many crates will travel on the sand ship?",
      "There are {a} supply crates at the dock. Leave {b} here. How many crates will travel on the sand ship?",
      [
        ["Food crates", "Tool crates"],
        ["At the dock", "Stay here"],
      ],
      "sail",
    ),
  ],
  sky: [
    mission(
      "wind",
      "Wake the wind turbines",
      "Wind workshop",
      -4,
      11,
      "wind sparks",
      "Read the wind collectors",
      "Start the turbines",
      "The sky harbour has power!",
      "Huge copper wind turbines spin above the clouds.",
      "One collector catches {a} wind sparks and the other catches {b}. How many sparks can power the turbines?",
      "The collector caught {a} wind sparks. {b} blew away. How many sparks can power the turbines?",
      [
        ["First collector", "Second collector"],
        ["Caught sparks", "Blew away"],
      ],
      "wind",
    ),
    mission(
      "balloon",
      "Rescue a stranded balloon",
      "Balloon mooring",
      6,
      9,
      "sandbags",
      "Check the ballast bags",
      "Free the balloon",
      "Up, up and away!",
      "The balloon rises gently above its landing platform.",
      "There are {a} sandbags on the left and {b} on the right. How many bags must the crew unload to float?",
      "The balloon carried {a} sandbags. The crew unloaded {b}. How many bags must they still unload?",
      [
        ["Left ballast", "Right ballast"],
        ["Original ballast", "Unloaded"],
      ],
      "balloon",
    ),
    mission(
      "mail",
      "Deliver the cloud post",
      "Airmail station",
      12,
      0,
      "parcels",
      "Sort the flight bags",
      "Send the mail glider",
      "Special delivery to the clouds!",
      "A little mail glider takes off with a trail of sparkling cloud dust.",
      "There are {a} parcels for Cloud Cottage and {b} for Windy Tower. How many parcels go on the glider?",
      "The station has {a} parcels. {b} are for this island. How many parcels must the glider deliver?",
      [
        ["Cloud Cottage", "Windy Tower"],
        ["At the station", "For this island"],
      ],
      "glider",
    ),
    mission(
      "chimes",
      "Build a rainbow of sound",
      "Sky chimes",
      5,
      -8,
      "music notes",
      "Read the music scrolls",
      "Ring the sky chimes",
      "The whole harbour is singing!",
      "Seven coloured chimes swing and light up above the clouds.",
      "The first tune has {a} notes. The second tune has {b}. How many notes are in the sky song?",
      "The sky song has {a} notes. The chimes played {b}. How many notes are still to play?",
      [
        ["First tune", "Second tune"],
        ["Whole song", "Already played"],
      ],
      "chimes",
    ),
    mission(
      "airship",
      "Launch the cloud cruiser",
      "Airship dock",
      -4,
      -7,
      "fuel cells",
      "Inspect the flight batteries",
      "Launch the airship",
      "Your cloud cruiser is flying!",
      "A giant airship lifts from its mooring and cruises over the harbour.",
      "One battery has {a} fuel cells and the other has {b}. How many fuel cells can launch the airship?",
      "The dock has {a} fuel cells. Save {b} for tomorrow. How many fuel cells can launch the airship?",
      [
        ["First battery", "Second battery"],
        ["At the dock", "Save for tomorrow"],
      ],
      "airship",
    ),
  ],
  moon: [
    mission(
      "solar",
      "Unfold the solar farm",
      "Solar station",
      5,
      12,
      "solar cells",
      "Inspect the solar crates",
      "Unfold the panels",
      "Sunshine becomes moon power!",
      "Blue solar wings unfold beside the lunar base.",
      "One crate has {a} solar cells and another has {b}. How many cells can power the solar farm?",
      "There are {a} solar cells. {b} are damaged. How many working cells can power the solar farm?",
      [
        ["First crate", "Second crate"],
        ["All cells", "Damaged cells"],
      ],
      "solar",
    ),
    mission(
      "rover",
      "Send the crater rover",
      "Rover garage",
      12,
      5,
      "moon rocks",
      "Read the rock sample list",
      "Deploy the rover",
      "The rover is exploring the crater!",
      "A six-wheeled rover rolls out on a rock-collecting expedition.",
      "Collect {a} pale moon rocks and {b} dark moon rocks. How many rocks will the rover bring back?",
      "The rover found {a} moon rocks. Leave {b} for another explorer. How many rocks will it bring back?",
      [
        ["Pale rocks", "Dark rocks"],
        ["Found rocks", "Leave behind"],
      ],
      "rover",
    ),
    mission(
      "habitat",
      "Inflate a moon habitat",
      "Habitat laboratory",
      8,
      -4,
      "air canisters",
      "Check the oxygen tanks",
      "Inflate the habitat",
      "A cosy home on the moon!",
      "A new habitat rises with glowing windows and its own airlock.",
      "One tank has {a} air canisters and the other has {b}. How many canisters can fill the habitat?",
      "The store has {a} air canisters. Save {b} for spacesuits. How many canisters can fill the habitat?",
      [
        ["First tank", "Second tank"],
        ["In the store", "For spacesuits"],
      ],
      "habitat",
    ),
    mission(
      "signal",
      "Phone home from the moon",
      "Deep-space antenna",
      -4,
      -7,
      "signal pulses",
      "Read the message monitor",
      "Send a message home",
      "Hello, Earth! Can you hear us?",
      "A giant antenna turns towards Earth and sends a glowing signal.",
      "One message has {a} signal pulses and another has {b}. How many pulses will the antenna send?",
      "The message needs {a} pulses. The antenna sent {b}. How many pulses are still waiting?",
      [
        ["First message", "Second message"],
        ["Whole message", "Already sent"],
      ],
      "dish",
    ),
    mission(
      "rocket",
      "Launch the star explorer",
      "Rocket launchpad",
      -4,
      3,
      "fuel units",
      "Check the rocket tanks",
      "Launch the rocket",
      "Next stop: the stars!",
      "The rocket lights its engines and climbs into the starry sky.",
      "The main tank holds {a} fuel units and the booster holds {b}. How many units can launch the rocket?",
      "The fuel tank held {a} units. The engine test used {b}. How many fuel units are left for the launch?",
      [
        ["Main tank", "Booster"],
        ["Before the test", "Used in the test"],
      ],
      "launch",
    ),
  ],
};
